In [3]:
sum([10,20,30])

60

In [4]:
lst = [1,2,3]
sum(lst)

6

In [5]:
len(lst)

3

In [7]:
len(range(1,5))

4

In [8]:
print(sum(lst)/len(lst))

2.0


In [10]:
# Numpy library and their functions
# The base vairant of python doesnot
# have all the mean and average of lists
# hence it makes the python fast.
# To access those we need numpy

In [11]:
import numpy as np

In [16]:
np.mean(lst).item()

2.0

In [19]:
# Linearly spaced numbers between start and stop divided by the total number of steps
np.linspace(1,8,20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [21]:
number = [1,2,3,4,5]
numbernp = np.array(number)
print(type(number))
print(type(numbernp))

<class 'list'>
<class 'numpy.ndarray'>


In [24]:
print(numbernp.min())

1


In [25]:
print(numbernp.max())

5


In [26]:
n = [4,3,7,8,1,4,3,9]
print(n)
n.sort()

[4, 3, 7, 8, 1, 4, 3, 9]


In [27]:
n

[1, 3, 3, 4, 4, 7, 8, 9]

In [28]:
print(type(n))
n1 = np.sort(n)
print(type(n1))

<class 'list'>
<class 'numpy.ndarray'>


In [29]:
# Pandas

In [1]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [4]:
var1 = np.random.randn(100)*5 + 20

In [5]:
var1

array([21.53421016, 22.45138312, 21.92192729, 22.09398778, 16.46412169,
       26.12807447, 15.84094113, 23.03261178, 18.1130488 , 25.32713632,
       26.69020001, 23.47234752, 19.14726857, 22.16387269, 16.17763119,
       22.5256329 , 17.20454172, 21.55953449, 21.06025245, 13.98259115,
       35.56493788, 24.06782501, 22.25144324, 16.73275116, 18.98520763,
       17.87988669, 18.30077375, 26.65654579, 20.38539025, 19.85289238,
       25.91564439, 23.73953358, 22.28443835, 20.41239352, 23.31435808,
       19.59570563, 27.39458941, 21.24981368, 19.96347188, 24.52495025,
       17.35773854, 24.78212364, 14.68166387, 23.49877482, 17.66276331,
       24.17771873, 17.33764687, 21.75794467, 15.30494481, 20.08274002,
       20.16879949, 20.97004382, 24.21247191, 21.99181481, 11.27296958,
       27.81700469, 12.03894284, 28.44488766, 19.45029273, 21.85235352,
       23.15984434, 18.81977185, 18.7546354 ,  2.97021785, 19.11953133,
       24.55189675, 23.84565602, 11.32360871, 18.52143139, 22.63

In [9]:
np.mean(var1)
# variance of 5 and mean of 20
# Hence mean should be around 20

np.float64(20.19315473602889)

In [10]:
var2 = np.random.randn(100)>0

In [11]:
var2

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False,  True, False, False, False,  True,  True,  True,
       False, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False, False, False, False,  True,
       False,  True,  True, False,  True, False, False, False,  True,
       False,  True, False,  True, False,  True, False, False, False,
        True, False, False,  True,  True, False, False, False, False,
       False])

In [12]:
labels = ['Temp. (C)', 'Ice cream eaten?']

In [13]:
# organizing the data of dictionary as a proper dataframe
D ={labels[0]: var1, labels[1]: var2}

In [14]:
df = pd.DataFrame(data=D)

In [15]:
df

Temp. (C)  Ice cream eaten?
0   21.534210              True
1   22.451383              True
2   21.921927              True
3   22.093988              True
4   16.464122              True
..        ...               ...
95  28.367814             False
96  22.175499             False
97  14.267523             False
98   8.078508             False
99  23.787975             False

[100 rows x 2 columns]

In [17]:
df.head(12)

Temp. (C)  Ice cream eaten?
0   21.534210              True
1   22.451383              True
2   21.921927              True
3   22.093988              True
4   16.464122              True
5   26.128074             False
6   15.840941              True
7   23.032612              True
8   18.113049              True
9   25.327136             False
10  26.690200             False
11  23.472348              True

In [18]:
df.count()

Temp. (C)           100
Ice cream eaten?    100
dtype: int64

In [19]:
df.mean()

Temp. (C)           20.193155
Ice cream eaten?     0.500000
dtype: float64

In [20]:
# Exercise
# 1) integers from 0 to 10
# 2) their squares
# 3) their logs

In [23]:
var1 = np.array(range(0,11))
var2 = np.pow(var1, 2)
var3 = np.log(var1)

C:\Users\sunni\AppData\Local\Temp\ipykernel_30328\2161507900.py:3: RuntimeWarning: divide by zero encountered in log
  var3 = np.log(var1)


In [24]:
labels = ['integer', 'squares', 'logs']


In [25]:
D = {labels[0]: var1, labels[1]: var2, labels[2]: var3}

In [26]:
df = pd.DataFrame(data=D)

In [27]:
df

integer  squares      logs
0         0        0      -inf
1         1        1  0.000000
2         2        4  0.693147
3         3        9  1.098612
4         4       16  1.386294
5         5       25  1.609438
6         6       36  1.791759
7         7       49  1.945910
8         8       64  2.079442
9         9       81  2.197225
10       10      100  2.302585

In [28]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [29]:
import inspect

In [30]:
inspect.getsourcelines(np.mean)

(['@array_function_dispatch(_mean_dispatcher)\n',
  'def mean(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, *,\n',
  '         where=np._NoValue):\n',
  '    """\n',
  '    Compute the arithmetic mean along the specified axis.\n',
  '\n',
  '    Returns the average of the array elements.  The average is taken over\n',
  '    the flattened array by default, otherwise over the specified axis.\n',
  '    `float64` intermediate and return values are used for integer inputs.\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    a : array_like\n',
  '        Array containing numbers whose mean is desired. If `a` is not an\n',
  '        array, a conversion is attempted.\n',
  '    axis : None or int or tuple of ints, optional\n',
  '        Axis or axes along which the means are computed. The default is to\n',
  '        compute the mean of the flattened array.\n',
  '\n',
  '        If this is a tuple of ints, a mean is performed over multiple axes,\n',
  '        inste